move_group_name: manipulator
tool_frame: flange

planning_trials: 30
reps_query: 10

planning_time: 30
planners:
#- mixed_strategy_b
#- timebased
- hamp_timebased

planner_baseline: mixed_strategy_a # Note: this planner should not be present in "planners"
planning_time_baseline: 30

#- probabilistic_hamp_time_based

occ_center:
- 1.5
- 0
- 1

occ_radius:
- 0.5
- 0.5
- 0.5

occupancy_cone_radius: 1.0

minimum_distance_from_start_to_goal: 1.0 # meters

limit_goal_workspace: true
ws_limits:
  box_center:
    - 1
    - 0
    - 1
  box_size:
    - 2
    - 2
    - 2
